# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\19144\Desktop\通信原理\computer.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(914, 1040)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, -10, 511, 111))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.pushButton_17 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_17.setGeometry(QtCore.QRect(590, 10, 311, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_17.setFont(font)
        self.pushButton_17.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_17.setObjectName("pushButton_17")
        self.pushButton_18 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_18.setGeometry(QtCore.QRect(590, 90, 311, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_18.setFont(font)
        self.pushButton_18.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_18.setObjectName("pushButton_18")
        self.pushButton_19 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_19.setGeometry(QtCore.QRect(590, 170, 151, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_19.setObjectName("pushButton_19")
        self.pushButton_20 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_20.setGeometry(QtCore.QRect(590, 250, 311, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_20.setFont(font)
        self.pushButton_20.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_20.setObjectName("pushButton_20")
        self.pushButton_21 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_21.setGeometry(QtCore.QRect(590, 330, 311, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_21.setFont(font)
        self.pushButton_21.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_21.setObjectName("pushButton_21")
        self.textEdit_2 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_2.setGeometry(QtCore.QRect(590, 410, 311, 491))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.textEdit_2.setFont(font)
        self.textEdit_2.setStyleSheet("QTextEdit {\n"
"    background-color: #f0f8ff; /* 背景颜色 */\n"
"    color: #333; /* 字体颜色 */\n"
"    border: 2px solid #87cefa; /* 边框颜色 */\n"
"    border-radius: 8px; /* 圆角边框 */\n"
"    padding: 10px; /* 内边距 */\n"
"    font-size: 16px; /* 字体大小 */\n"
"    font-family: Arial, sans-serif; /* 字体 */\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #00bfff; /* 聚焦时边框颜色 */\n"
"    background-color: #e6f9ff; /* 聚焦时背景颜色 */\n"
"}")
        self.textEdit_2.setObjectName("textEdit_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 780, 341, 251))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label.setObjectName("label")
        self.textEdit_3 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_3.setGeometry(QtCore.QRect(10, 90, 571, 151))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.textEdit_3.setFont(font)
        self.textEdit_3.setStyleSheet("QTextEdit {\n"
"    background-color: #f0f8ff; /* 背景颜色 */\n"
"    color: #333; /* 字体颜色 */\n"
"    border: 2px solid #87cefa; /* 边框颜色 */\n"
"    border-radius: 8px; /* 圆角边框 */\n"
"    padding: 10px; /* 内边距 */\n"
"    font-size: 16px; /* 字体大小 */\n"
"    font-family: Arial, sans-serif; /* 字体 */\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #00bfff; /* 聚焦时边框颜色 */\n"
"    background-color: #e6f9ff; /* 聚焦时背景颜色 */\n"
"}")
        self.textEdit_3.setObjectName("textEdit_3")
        self.pushButton_22 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 250, 281, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_22.setFont(font)
        self.pushButton_22.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_22.setObjectName("pushButton_22")
        self.pushButton_23 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_23.setGeometry(QtCore.QRect(300, 250, 281, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_23.setFont(font)
        self.pushButton_23.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_23.setObjectName("pushButton_23")
        self.pushButton_24 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_24.setGeometry(QtCore.QRect(750, 170, 151, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_24.setFont(font)
        self.pushButton_24.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_24.setObjectName("pushButton_24")
        self.textEdit_4 = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit_4.setGeometry(QtCore.QRect(10, 410, 571, 271))
        font = QtGui.QFont()
        font.setFamily("Arial,sans-serif")
        font.setPointSize(-1)
        self.textEdit_4.setFont(font)
        self.textEdit_4.setStyleSheet("QTextEdit {\n"
"    background-color: #f0f8ff; /* 背景颜色 */\n"
"    color: #333; /* 字体颜色 */\n"
"    border: 2px solid #87cefa; /* 边框颜色 */\n"
"    border-radius: 8px; /* 圆角边框 */\n"
"    padding: 10px; /* 内边距 */\n"
"    font-size: 16px; /* 字体大小 */\n"
"    font-family: Arial, sans-serif; /* 字体 */\n"
"}\n"
"\n"
"QTextEdit:focus {\n"
"    border: 2px solid #00bfff; /* 聚焦时边框颜色 */\n"
"    background-color: #e6f9ff; /* 聚焦时背景颜色 */\n"
"}")
        self.textEdit_4.setObjectName("textEdit_4")
        self.checkBox = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(10, 330, 571, 71))
        self.checkBox.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBox.setFont(font)
        self.checkBox.setIconSize(QtCore.QSize(30, 30))
        self.checkBox.setObjectName("checkBox")
        self.pushButton_25 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_25.setGeometry(QtCore.QRect(440, 690, 141, 41))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_25.setFont(font)
        self.pushButton_25.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_25.setObjectName("pushButton_25")
        self.checkBox_2 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_2.setGeometry(QtCore.QRect(10, 690, 381, 71))
        self.checkBox_2.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_2.setObjectName("checkBox_2")
        self.pushButton_26 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_26.setGeometry(QtCore.QRect(590, 910, 311, 71))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.pushButton_26.setFont(font)
        self.pushButton_26.setStyleSheet("QPushButton{color:#fff;background-color:#409eff;border: 1px solid #409eff;border-radius: 10px;\n"
"}QPushButton:hover{color:#fff;border-color:#66b1ff;background-color:#66b1ff;\n"
"}QPushButton:checked{color:#fff;border-color:#66b1ff;background-color: #66b1ff;\n"
"}QPushButton:pressed{color:#fff;border-color: #3a8ee6;background-color: #3a8ee6;\n"
"}\n"
"")
        self.pushButton_26.setObjectName("pushButton_26")
        self.spinBox = QtWidgets.QSpinBox(self.centralwidget)
        self.spinBox.setGeometry(QtCore.QRect(430, 920, 151, 51))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(18)
        self.spinBox.setFont(font)
        self.spinBox.setStyleSheet("QSpinBox{color:#fff;background-color:#409eff;border: 5px solid #409eff;border-radius: 15px;\n"
"}\n"
"")
        self.spinBox.setMaximum(200)
        self.spinBox.setProperty("value", 10)
        self.spinBox.setObjectName("spinBox")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(440, 740, 141, 51))
        self.lineEdit.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f8ff; /* 背景颜色 */\n"
"    color: #333; /* 字体颜色 */\n"
"    border: 2px solid #87cefa; /* 边框颜色 */\n"
"    border-radius: 8px; /* 圆角边框 */\n"
"    padding: 10px; /* 内边距 */\n"
"    font-size: 16px; /* 字体大小 */\n"
"    font-family: Arial, sans-serif; /* 字体 */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00bfff; /* 聚焦时边框颜色 */\n"
"    background-color: #e6f9ff; /* 聚焦时背景颜色 */\n"
"}")
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(340, 730, 101, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_2.setGeometry(QtCore.QRect(440, 800, 141, 51))
        self.lineEdit_2.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f8ff; /* 背景颜色 */\n"
"    color: #333; /* 字体颜色 */\n"
"    border: 2px solid #87cefa; /* 边框颜色 */\n"
"    border-radius: 8px; /* 圆角边框 */\n"
"    padding: 10px; /* 内边距 */\n"
"    font-size: 16px; /* 字体大小 */\n"
"    font-family: Arial, sans-serif; /* 字体 */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00bfff; /* 聚焦时边框颜色 */\n"
"    background-color: #e6f9ff; /* 聚焦时背景颜色 */\n"
"}")
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setEnabled(False)
        self.label_3.setGeometry(QtCore.QRect(340, 790, 101, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setEnabled(False)
        self.lineEdit_3.setGeometry(QtCore.QRect(440, 860, 141, 51))
        self.lineEdit_3.setStyleSheet("QLineEdit {\n"
"    background-color: #f0f8ff; /* 背景颜色 */\n"
"    color: #333; /* 字体颜色 */\n"
"    border: 2px solid #87cefa; /* 边框颜色 */\n"
"    border-radius: 8px; /* 圆角边框 */\n"
"    padding: 10px; /* 内边距 */\n"
"    font-size: 16px; /* 字体大小 */\n"
"    font-family: Arial, sans-serif; /* 字体 */\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border: 2px solid #00bfff; /* 聚焦时边框颜色 */\n"
"    background-color: #e6f9ff; /* 聚焦时背景颜色 */\n"
"}")
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setEnabled(False)
        self.label_4.setGeometry(QtCore.QRect(340, 850, 101, 61))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.checkBox_3 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 730, 381, 71))
        self.checkBox_3.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBox_3.setFont(font)
        self.checkBox_3.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_3.setChecked(True)
        self.checkBox_3.setObjectName("checkBox_3")
        self.checkBox_4 = QtWidgets.QCheckBox(self.centralwidget)
        self.checkBox_4.setGeometry(QtCore.QRect(10, 770, 381, 71))
        self.checkBox_4.setMinimumSize(QtCore.QSize(30, 30))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.checkBox_4.setFont(font)
        self.checkBox_4.setIconSize(QtCore.QSize(30, 30))
        self.checkBox_4.setChecked(False)
        self.checkBox_4.setObjectName("checkBox_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 914, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_6.setText(_translate("MainWindow", "计算式输入"))
        self.pushButton_17.setText(_translate("MainWindow", "编码"))
        self.pushButton_18.setText(_translate("MainWindow", "发送"))
        self.pushButton_19.setText(_translate("MainWindow", "开始录音"))
        self.pushButton_20.setText(_translate("MainWindow", "解码"))
        self.pushButton_21.setText(_translate("MainWindow", "计算"))
        self.textEdit_2.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial,sans-serif\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24px;\"><br /></p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:500;\">通信原理——无线计算机</span></p><p><span style=\" font-size:12pt; font-weight:500;\">仅供学习使用</span></p><p><span style=\" font-size:12pt; font-weight:500;\">指导老师：杨敬钰</span></p><p><span style=\" font-size:12pt; font-weight:500;\">参与：王烨豪，高明奇</span></p></body></html>"))
        self.textEdit_3.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial,sans-serif\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24px;\"><br /></p></body></html>"))
        self.pushButton_22.setText(_translate("MainWindow", "清空输入"))
        self.pushButton_23.setText(_translate("MainWindow", "完成输入"))
        self.pushButton_24.setText(_translate("MainWindow", "停止录音"))
        self.textEdit_4.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Arial,sans-serif\'; font-size:16px; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:24px;\"><br /></p></body></html>"))
        self.checkBox.setText(_translate("MainWindow", "请问你是接收方吗？是的话请勾上"))
        self.pushButton_25.setText(_translate("MainWindow", "清空"))
        self.checkBox_2.setText(_translate("MainWindow", "是否开启重传功能？"))
        self.pushButton_26.setText(_translate("MainWindow", "连续发送n次（左）"))
        self.label_2.setText(_translate("MainWindow", "结果"))
        self.label_3.setText(_translate("MainWindow", "正确次数"))
        self.label_4.setText(_translate("MainWindow", "正确率"))
        self.checkBox_3.setText(_translate("MainWindow", "是否使用编码？"))
        self.checkBox_4.setText(_translate("MainWindow", "显示图像"))
